name: linkcheck

on:
  pull_request:
    branches:
      - openriak-3.4
  push:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tcort/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
        folder-path: './docs/'
        file-path: './README.md'
        max-depth: 2